### PR TITLE
Exit jpsreport, if measurement are is misconfigured.

### LINKED ISSUE #706: jpsreport: Method D with a measurement method out of bounds
What happens actually if the measurement method is not in the geometry?

`jpsreport` gives the following error: 

```
ERROR: 	 No polygon containing the measurement id [1]
```

and goes on by producing a ton of warnings

```
Warning:	Pedestrian at <x=-4.0851, y=4.1511> is not in geometry and not considered in analysis!
```

then ends with an optimistic message 

```
INFO:	Success with Method D using measurement area id 1!
```

In this case this [if](https://github.com/JuPedSim/jpscore/blob/master/jpsreport/Analysis.cpp#L234) is not entered, so that `geoPoly[area->_id]` does not get initialised.

How do you suggest to deal with this situation?

******

JuPedSim - JPSreport

Current date   : Fri Feb 21 14:47:21 2020
Version        : 0.8.4
Compiler       : clang++ (11.0.0)
Commit hash    : v0.8.4-923-geaf22278
Commit date    : Thu Feb 20 19:18:20 2020
Branch         : master

### PR DESCRIPTION
**Pull request by chraibi**
There is not a sane case where this situation should be tolerated.
Therefore, exit calculation at once. The user is expected to
configure measurement areas properly.

Fixes  #706

### CODE REVIEW

File: jpsreport/Analysis.cpp [hunk 1]
```diff
@@ -264,6 +264,7 @@ std::map<int, polygon_2d> Analysis::ReadGeometry(
 
         if(geoPoly.count(area->_id) == 0) {
             Log->Write("ERROR: \t No polygon containing the measurement id [%d]", area->_id);
+            exit(EXIT_FAILURE);
```
Comment (schroedtert) [inline jpsreport/Analysis.cpp:267]: I suggest that we do not use exit not during the run of the program but instead throw exceptions. These exception should be caught on top level. Similar to jpscore (see main.cpp)

Comment (schroedtert) [inline jpsreport/Analysis.cpp:267]: There should be no code after a exit/exception as will never be called

File: jpsreport/methods/Method_D.cpp [hunk 2]
```diff
@@ -131,11 +131,6 @@ bool Method_D::Process(
         //------------------------------Remove peds outside geometry------------------------------------------
         for(int i = 0; i < (int) IdInFrame.size(); i++) {
             if(false == within(point_2d(round(XInFrame[i]), round(YInFrame[i])), _geoPoly)) {
-                Log->Write(
-                    "Warning:\tPedestrian at <x=%.4f, y=%.4f> is not in geometry and not "
-                    "considered in analysis!",
-                    XInFrame[i] * CMtoM,
-                    YInFrame[i] * CMtoM);
```
Comment (zeroset) [inline jpsreport/methods/Method_D.cpp:138]: Why did you remove this?

Comment (chraibi) [reply jpsreport/methods/Method_D.cpp]: because sometimes when the geometry does not fit the trajectories, there are tones of warnings and that's very noisy.
